### ISSUE TITLE
Make imagePullPolicy configurable for xrally kubernetes tests

### ISSUE THREAD

**Issue by msidana** [Mirantis/rally-plugins#4]
In xrally tests, the image policy is set to ```Always```. This should be made configurable so that the ```imagePullPolicy``` can be set appropriately depending on different environments. This will also help to execute the tests successfully in cluster which do not have internet connectivity or connectivity to docket hub. In this case, container images can. simply be uploaded to worker nodes and the tests can execute with ```IfNotPresent``` policy

**Comment by olegeech-me** [comment]
hey @msidana 
thanks for raising it up, I'll be working on that shortly.
